"""Add updated_at to messages

Revision ID: 189a14260016
Revises: 0ccfb04b6cd9
Create Date: 2026-04-10 09:31:17.997927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189a14260016'
down_revision = '0ccfb04b6cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
