"""Add duration to files_attachments

Revision ID: 803eb31e4a6a
Revises: 47af74e625dd
Create Date: 2026-04-13 13:04:12.563599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803eb31e4a6a'
down_revision = '47af74e625dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_attachments', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
