"""Update FileAttachment model: message_id nullable and rename file_url

Revision ID: 94fa63f0fec9
Revises: 189a14260016
Create Date: 2026-04-10 09:56:12.724386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fa63f0fec9'
down_revision = '189a14260016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=512), nullable=False))
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('firebase_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
